[window]
opacity = 1.0

[font]
builtin_box_drawing = true
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
offset.y = 2
size=13

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor]
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.8
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.8
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 4.0
smooth_motion_max_stretch_y = 4.0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

# Gruvbox
[colors.primary]
background = '#1b1d24'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
